import type { BuildingDef, ProjectDef } from '../types';

const Y = (ind = 0, res = 0, pro = 0) => ({ ind, res, pro });

export const BUILDINGS: BuildingDef[] = [
  // --- Surface: core economy ---------------------------------------------
  { id: 'factory', name: 'Factory', role: 'industry', orbital: false, yield: Y(2), housing: 0, cost: 30, needsWorker: true,
    desc: 'Basic industry. Doubled on red tiles.' },
  { id: 'agridome', name: 'Agridome', role: 'prosperity', orbital: false, yield: Y(0, 0, 2), housing: 0, cost: 30, needsWorker: true,
    desc: 'Food and comfort; prosperity drives population growth. Doubled on green tiles.' },
  { id: 'lab', name: 'Laboratory', role: 'research', orbital: false, yield: Y(0, 2), housing: 0, cost: 45, needsWorker: true,
    desc: 'Basic research. Doubled on blue tiles.' },
  { id: 'colonybase', name: 'Landing Hub', role: 'mixed', orbital: false, yield: Y(1, 1, 1), housing: 2, cost: 100, needsWorker: false, unique: true,
    desc: 'The first structure on every colony. Houses two and needs no workers.' },
  { id: 'habitat', name: 'Hab Dome', role: 'housing', orbital: false, yield: Y(), housing: 3, cost: 110, tech: 'envseal', needsWorker: false,
    desc: '+3 population capacity. Needs no workers.' },
  { id: 'metroplex', name: 'Arcology', role: 'mixed', orbital: false, yield: Y(1, 1, 1), housing: 3, cost: 190, tech: 'largeconst', needsWorker: true,
    desc: 'Dense arcology: a little of everything, plus housing.' },
  { id: 'megaplex', name: 'Industrial Megaplex', role: 'industry', orbital: false, yield: Y(4), housing: 0, cost: 120, tech: 'megafab', needsWorker: true, upgrades: 'factory',
    desc: 'Heavy industry. Replaces factories when auto-upgrade is on.' },
  { id: 'hydrospire', name: 'Hydroponic Spire', role: 'prosperity', orbital: false, yield: Y(0, 0, 4), housing: 0, cost: 110, tech: 'hydroponics', needsWorker: true, upgrades: 'agridome',
    desc: 'Vertical farm. Replaces agridomes when auto-upgrade is on.' },
  { id: 'campus', name: 'Think Spire', role: 'research', orbital: false, yield: Y(0, 4), housing: 0, cost: 160, tech: 'hyperlogic', needsWorker: true, upgrades: 'lab',
    desc: 'A university city. Replaces laboratories when auto-upgrade is on.' },
  { id: 'retreat', name: 'Foundry Academy', role: 'mixed', orbital: false, yield: Y(3, 3), housing: 0, cost: 170, tech: 'automation', needsWorker: true,
    desc: 'Engineers and theorists sharing one campus.' },
  { id: 'fusionhub', name: 'Fusion Hub', role: 'special', orbital: false, yield: Y(), housing: 0, cost: 200, tech: 'hyperpower', needsWorker: true, unique: true, bonus: { ind: 0.5 },
    desc: '+50% industry on this planet.' },
  { id: 'datasphere', name: 'Mindweb Node', role: 'special', orbital: false, yield: Y(), housing: 0, cost: 240, tech: 'datasphere', needsWorker: true, unique: true, bonus: { res: 0.5 },
    desc: '+50% research on this planet.' },
  { id: 'biosphere', name: 'Biosphere Regulator', role: 'special', orbital: false, yield: Y(), housing: 2, cost: 220, tech: 'biosphere', needsWorker: true, unique: true, bonus: { pro: 0.5 },
    desc: '+50% prosperity and +2 capacity on this planet.' },
  { id: 'cloningvats', name: 'Growth Vats', role: 'housing', orbital: false, yield: Y(0, 0, 3), housing: 2, cost: 160, tech: 'cloning', needsWorker: true,
    desc: 'Growth tanks: prosperity and housing.' },
  // --- Surface: utility & defense ---------------------------------------
  { id: 'observatory', name: 'Observatory', role: 'special', orbital: false, yield: Y(0, 1), housing: 0, cost: 40, tech: 'data', needsWorker: true, unique: true, scan: 280,
    desc: 'Watches nearby lanes (sensor range) and contributes a little research.' },
  { id: 'garrison', name: 'Garrison', role: 'defense', orbital: false, yield: Y(), housing: 0, cost: 60, tech: 'assault', needsWorker: false,
    desc: 'Troops that resist invasion (+8 defense each).' },
  { id: 'surfshield', name: 'Planetary Aegis', role: 'defense', orbital: false, yield: Y(), housing: 0, cost: 100, tech: 'deflectors', needsWorker: false, unique: true,
    desc: 'Blocks invasion entirely while orbital defenses stand.' },
  { id: 'surfcloak', name: 'Veil Generator', role: 'defense', orbital: false, yield: Y(), housing: 0, cost: 60, tech: 'cloaking', needsWorker: false, unique: true,
    desc: 'Hides this planet from rival sensors.' },
  { id: 'excavation', name: 'Excavation Site', role: 'special', orbital: false, yield: Y(), housing: 0, cost: 60, tech: 'xenoarch', needsWorker: false, unique: true,
    desc: 'Dig the ruins on this planet. The reward was fixed when the galaxy formed; reloading will not change it.' },
  // --- Orbital -----------------------------------------------------------
  { id: 'shipyard', name: 'Shipyard', role: 'shipyard', orbital: true, yield: Y(), housing: 0, cost: 120, needsWorker: false, unique: true,
    desc: 'Builds and refits ships.' },
  { id: 'docks', name: 'Drydock Ring', role: 'shipyard', orbital: true, yield: Y(1), housing: 0, cost: 170, tech: 'megafab', needsWorker: false, unique: true,
    desc: 'Ships built here cost 25% less; fleets here repair fully each day.' },
  { id: 'solararray', name: 'Solar Array', role: 'industry', orbital: true, yield: Y(2), housing: 0, cost: 70, tech: 'orbital', needsWorker: false,
    desc: 'Orbital collectors: industry with no workers.' },
  { id: 'researchstation', name: 'Research Station', role: 'research', orbital: true, yield: Y(0, 2), housing: 0, cost: 90, tech: 'spectral', needsWorker: false,
    desc: 'Orbital laboratory: research with no workers.' },
  { id: 'habring', name: 'Habitat Ring', role: 'housing', orbital: true, yield: Y(0, 0, 1), housing: 4, cost: 200, tech: 'megastruct', needsWorker: false,
    desc: '+4 population capacity in orbit.' },
  { id: 'missilebase', name: 'Missile Battery', role: 'defense', orbital: true, yield: Y(), housing: 0, cost: 60, tech: 'kinetics', needsWorker: false,
    defense: { hp: 40, damage: 3, range: 400, shots: 2 }, desc: 'Orbital missile launchers.' },
  { id: 'lance', name: 'Lance Platform', role: 'defense', orbital: true, yield: Y(), housing: 0, cost: 110, tech: 'plasmatics', needsWorker: false,
    defense: { hp: 70, damage: 8, range: 300, shots: 1 }, desc: 'Short-range plasma lance.' },
  { id: 'heavylance', name: 'Heavy Lance Platform', role: 'defense', orbital: true, yield: Y(), housing: 0, cost: 180, tech: 'planetarms', needsWorker: false, upgrades: 'lance',
    defense: { hp: 120, damage: 11, range: 600, shots: 2 }, desc: 'Long-range lance battery.' },
  { id: 'orbshield', name: 'Orbital Aegis', role: 'defense', orbital: true, yield: Y(), housing: 0, cost: 70, tech: 'deflectors', needsWorker: false, unique: true,
    defense: { hp: 60, shield: 6 }, desc: 'Shields every orbital structure (+6 per round).' },
  { id: 'megashield', name: 'Aegis Lattice', role: 'defense', orbital: true, yield: Y(), housing: 0, cost: 150, tech: 'phasebarrier', needsWorker: false, unique: true, upgrades: 'orbshield',
    defense: { hp: 120, shield: 14 }, desc: 'Heavy orbital shield (+14 per round).' },
];

export const PROJECTS: ProjectDef[] = [
  { id: 'grants', name: 'Research Grants', desc: 'Converts half of this planet’s industry into research.' },
  { id: 'festival', name: 'Endless Festival', desc: 'Converts half of this planet’s industry into prosperity.' },
  { id: 'convoy', name: 'Supply Convoy', desc: 'Ships 60% of industry to the empire logistics pool, which speeds up construction on planets that need it.' },
  { id: 'outreach', name: 'Diplomatic Outreach', tech: 'linguistics', desc: 'Every empire you have met warms to you a little each month.' },
  { id: 'fortify', name: 'Fortify', tech: 'assault', desc: 'Drills the militia: raises invasion defense over time.' },
];
