// Shared three.js building blocks for every 3D view (system, battle, galaxy,
// planet globe). Models come from public/models/ (generated by Blender via
// tools/blender/build_assets.py); primitives are used as fallbacks when a
// model is missing, so views always render.

import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { planetEquirect, STAR_COLORS } from '../art/procedural';
import type { StarClass } from '../sim/types';

// --- renderer -------------------------------------------------------------------

export interface Stage {
  renderer: THREE.WebGLRenderer;
  scene: THREE.Scene;
  camera: THREE.PerspectiveCamera;
  host: HTMLElement;
  /** Call from your animation loop. */
  render(): void;
  dispose(): void;
  onResize?: (w: number, h: number) => void;
}

export function createStage(host: HTMLElement, opts: { fov?: number; near?: number; far?: number; background?: number } = {}): Stage {
  const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false, powerPreference: 'high-performance' });
  renderer.setPixelRatio(Math.min(2, window.devicePixelRatio || 1));
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  renderer.toneMappingExposure = 1.1;
  renderer.setClearColor(opts.background ?? 0x03040a, 1);
  host.appendChild(renderer.domElement);
  renderer.domElement.style.display = 'block';
  const scene = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(opts.fov ?? 45, 1, opts.near ?? 0.1, opts.far ?? 5000);
  const stage: Stage = {
    renderer, scene, camera, host,
    render: () => renderer.render(scene, camera),
    dispose: () => {
      ro.disconnect();
      scene.traverse((o) => {
        const m = o as THREE.Mesh;
        m.geometry?.dispose?.();
        const mats = Array.isArray(m.material) ? m.material : m.material ? [m.material] : [];
        for (const mat of mats) (mat as THREE.Material).dispose();
      });
      renderer.dispose();
      renderer.domElement.remove();
    },
  };
  const resize = () => {
    const w = Math.max(1, host.clientWidth), h = Math.max(1, host.clientHeight);
    renderer.setSize(w, h, false);
    renderer.domElement.style.width = w + 'px';
    renderer.domElement.style.height = h + 'px';
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
    stage.onResize?.(w, h);
  };
  const ro = new ResizeObserver(resize);
  ro.observe(host);
  resize();
  return stage;
}

/** Distant starfield sphere. */
export function starfield(count = 2500, radius = 1500) {
  const g = new THREE.BufferGeometry();
  const pos = new Float32Array(count * 3);
  const col = new Float32Array(count * 3);
  for (let i = 0; i < count; i++) {
    const u = Math.random() * 2 - 1, t = Math.random() * Math.PI * 2, r = Math.sqrt(1 - u * u);
    pos.set([Math.cos(t) * r * radius, u * radius, Math.sin(t) * r * radius], i * 3);
    const k = 0.5 + Math.random() * 0.5;
    col.set([k, k, k * (0.9 + Math.random() * 0.2)], i * 3);
  }
  g.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  g.setAttribute('color', new THREE.BufferAttribute(col, 3));
  return new THREE.Points(g, new THREE.PointsMaterial({ size: 1.6, sizeAttenuation: false, vertexColors: true, depthWrite: false }));
}

// --- glow sprites ----------------------------------------------------------------

let glowTex: THREE.Texture | null = null;
export function glowTexture() {
  if (glowTex) return glowTex;
  const c = document.createElement('canvas');
  c.width = c.height = 128;
  const ctx = c.getContext('2d')!;
  const g = ctx.createRadialGradient(64, 64, 0, 64, 64, 64);
  g.addColorStop(0, 'rgba(255,255,255,1)');
  g.addColorStop(0.2, 'rgba(255,255,255,0.6)');
  g.addColorStop(1, 'rgba(255,255,255,0)');
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 128, 128);
  glowTex = new THREE.CanvasTexture(c);
  glowTex.colorSpace = THREE.SRGBColorSpace;
  return glowTex;
}

export function glowSprite(color: THREE.ColorRepresentation, size: number, opacity = 1) {
  const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTexture(), color, transparent: true, opacity, depthWrite: false, blending: THREE.AdditiveBlending }));
  s.scale.setScalar(size);
  return s;
}

// --- stars and planets --------------------------------------------------------------

export function makeStar(cls: StarClass, radius = 3) {
  const group = new THREE.Group();
  const color = new THREE.Color(STAR_COLORS[cls]);
  if (cls === 'BH') {
    group.add(new THREE.Mesh(new THREE.SphereGeometry(radius, 48, 32), new THREE.MeshBasicMaterial({ color: 0x000000 })));
    const disk = new THREE.Mesh(new THREE.RingGeometry(radius * 1.3, radius * 3, 96), new THREE.MeshBasicMaterial({ color: 0xd8a8ff, side: THREE.DoubleSide, transparent: true, opacity: 0.6, blending: THREE.AdditiveBlending }));
    disk.rotation.x = Math.PI / 2.3;
    group.add(disk);
    group.add(glowSprite(0x8050ff, radius * 8, 0.5));
    return group;
  }
  const core = new THREE.Mesh(new THREE.SphereGeometry(radius, 48, 32), new THREE.MeshBasicMaterial({ color: color.clone().lerp(new THREE.Color(0xffffff), 0.55) }));
  group.add(core);
  group.add(glowSprite(color, radius * 7, 0.9));
  group.add(glowSprite(0xffffff, radius * 3, 0.7));
  const light = new THREE.PointLight(color.clone().lerp(new THREE.Color(0xffffff), 0.5), 3, 0, 0);
  group.add(light);
  return group;
}

const planetTexCache = new Map<string, THREE.Texture>();

/** A lit planet with a procedural surface and a fresnel atmosphere shell. */
export function makePlanet(type: string, seed: number, radius = 1) {
  const key = `${type}:${seed}`;
  let tex = planetTexCache.get(key);
  const { canvas, atmo } = planetEquirect(type, seed, 512);
  if (!tex) {
    tex = new THREE.CanvasTexture(canvas);
    tex.colorSpace = THREE.SRGBColorSpace;
    tex.anisotropy = 4;
    planetTexCache.set(key, tex);
  }
  const group = new THREE.Group();
  const body = new THREE.Mesh(new THREE.SphereGeometry(radius, 64, 48), new THREE.MeshStandardMaterial({ map: tex, roughness: 0.85, metalness: 0.05 }));
  body.name = 'body';
  group.add(body);
  group.add(atmosphere(radius, atmo));
  if (type === 'gasgiant' || seed % 5 === 0) {
    const ring = new THREE.Mesh(
      new THREE.RingGeometry(radius * 1.4, radius * 2.1, 96),
      new THREE.MeshBasicMaterial({ color: new THREE.Color(atmo).multiplyScalar(0.8), side: THREE.DoubleSide, transparent: true, opacity: 0.35, depthWrite: false }),
    );
    ring.rotation.x = Math.PI / 2 - 0.35;
    ring.visible = type === 'gasgiant';
    group.add(ring);
  }
  return group;
}

export function atmosphere(radius: number, color: string) {
  const mat = new THREE.ShaderMaterial({
    uniforms: { c: { value: new THREE.Color(color) } },
    vertexShader: `varying vec3 vN; varying vec3 vV; void main(){ vN = normalize(normalMatrix * normal); vec4 mv = modelViewMatrix * vec4(position,1.0); vV = normalize(-mv.xyz); gl_Position = projectionMatrix * mv; }`,
    fragmentShader: `uniform vec3 c; varying vec3 vN; varying vec3 vV; void main(){ float f = pow(1.0 - max(dot(vN, vV), 0.0), 2.5); gl_FragColor = vec4(c, f * 0.9); }`,
    transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.FrontSide,
  });
  return new THREE.Mesh(new THREE.SphereGeometry(radius * 1.06, 48, 32), mat);
}

// --- glTF models ------------------------------------------------------------------

export interface ModelManifest {
  version: number;
  ships: Record<string, string>;
  stations: Record<string, string>;
  buildings: Record<string, string>;
}

let manifest: Promise<ModelManifest | null> | null = null;
const loader = new GLTFLoader();
const modelCache = new Map<string, Promise<THREE.Object3D | null>>();

export function modelManifest() {
  if (!manifest) manifest = fetch('./models/manifest.json').then((r) => (r.ok ? (r.json() as Promise<ModelManifest>) : null)).catch(() => null);
  return manifest;
}

function loadGlb(path: string) {
  let p = modelCache.get(path);
  if (!p) {
    p = loader.loadAsync('./models/' + path).then((g) => g.scene).catch(() => null);
    modelCache.set(path, p);
  }
  return p;
}

/**
 * Clone a model and tint it. Material naming contract (set in Blender):
 *   "Paint*" → empire color, "Glow*" → emissive accent, anything else untouched.
 */
export function tint(obj: THREE.Object3D, paint: THREE.ColorRepresentation, glow?: THREE.ColorRepresentation) {
  const c = obj.clone(true);
  c.traverse((o) => {
    const m = o as THREE.Mesh;
    if (!m.isMesh) return;
    const mats = Array.isArray(m.material) ? m.material : [m.material];
    m.material = mats.map((mat) => {
      const std = (mat as THREE.MeshStandardMaterial).clone();
      if (std.name.startsWith('Paint')) std.color = new THREE.Color(paint);
      if (std.name.startsWith('Glow')) {
        std.emissive = new THREE.Color(glow ?? paint);
        std.emissiveIntensity = 2.5;
      }
      return std;
    }) as unknown as THREE.Material;
    if (Array.isArray(m.material) && m.material.length === 1) m.material = m.material[0];
  });
  return c;
}

/** Ship family for a species style: 4 visual families of hulls. */
export const SHIP_FAMILIES = ['angular', 'organic', 'crystal', 'saucer'] as const;
export function shipKey(style: number, hull: string) {
  return `${SHIP_FAMILIES[style % SHIP_FAMILIES.length]}_${hull}`;
}

export async function shipModel(style: number, hull: string, color: THREE.ColorRepresentation): Promise<THREE.Object3D> {
  const m = await modelManifest();
  const path = m?.ships[shipKey(style, hull)];
  const src = path ? await loadGlb(path) : null;
  return src ? tint(src, color) : fallbackShip(hull, color);
}

export async function stationModel(kind: string, color: THREE.ColorRepresentation): Promise<THREE.Object3D> {
  const m = await modelManifest();
  const path = m?.stations[kind];
  const src = path ? await loadGlb(path) : null;
  return src ? tint(src, color) : fallbackStation(color);
}

export async function buildingModel(id: string, role: string, color: THREE.ColorRepresentation): Promise<THREE.Object3D> {
  const m = await modelManifest();
  const path = m?.buildings[id] ?? m?.buildings[role];
  const src = path ? await loadGlb(path) : null;
  return src ? tint(src, color) : fallbackBuilding(color);
}

const HULL_SCALE: Record<string, number> = { small: 0.5, medium: 0.7, large: 0.9, enormous: 1.15, titan: 1.4 };

/** Primitive ship (nose along +X) used until Blender models exist. */
export function fallbackShip(hull: string, color: THREE.ColorRepresentation) {
  const s = HULL_SCALE[hull] ?? 0.7;
  const g = new THREE.Group();
  const body = new THREE.Mesh(new THREE.ConeGeometry(0.25 * s, 1.2 * s, 6), new THREE.MeshStandardMaterial({ color, metalness: 0.6, roughness: 0.35 }));
  body.rotation.z = -Math.PI / 2;
  g.add(body);
  const eng = new THREE.Mesh(new THREE.SphereGeometry(0.12 * s, 12, 8), new THREE.MeshStandardMaterial({ color: 0x000000, emissive: 0x7fdcff, emissiveIntensity: 3 }));
  eng.position.x = -0.6 * s;
  g.add(eng);
  return g;
}

export function fallbackStation(color: THREE.ColorRepresentation) {
  const g = new THREE.Group();
  g.add(new THREE.Mesh(new THREE.TorusGeometry(0.5, 0.08, 8, 24), new THREE.MeshStandardMaterial({ color, metalness: 0.7, roughness: 0.3 })));
  g.add(new THREE.Mesh(new THREE.OctahedronGeometry(0.2), new THREE.MeshStandardMaterial({ color: 0xdddddd, metalness: 0.6, roughness: 0.4 })));
  return g;
}

export function fallbackBuilding(color: THREE.ColorRepresentation) {
  return new THREE.Mesh(new THREE.BoxGeometry(0.6, 0.5, 0.6), new THREE.MeshStandardMaterial({ color, roughness: 0.6 }));
}

// --- simple orbit camera ------------------------------------------------------------

/**
 * Minimal orbit/pan/zoom camera controller (no dependency on OrbitControls so
 * we can clamp tilt for the "flat plane, tiltable camera" style).
 */
export class OrbitRig {
  target = new THREE.Vector3();
  yaw = 0;
  pitch = 0.9;
  dist = 30;
  minPitch = 0.15;
  maxPitch = 1.45;
  minDist = 2;
  maxDist = 4000;
  private drag: { x: number; y: number; button: number } | null = null;
  moved = 0;

  constructor(private camera: THREE.PerspectiveCamera, private el: HTMLElement) {
    el.addEventListener('pointerdown', this.down);
    window.addEventListener('pointermove', this.move);
    window.addEventListener('pointerup', this.up);
    el.addEventListener('wheel', this.wheel, { passive: false });
    el.addEventListener('contextmenu', (e) => e.preventDefault());
    this.update();
  }

  dispose() {
    this.el.removeEventListener('pointerdown', this.down);
    window.removeEventListener('pointermove', this.move);
    window.removeEventListener('pointerup', this.up);
    this.el.removeEventListener('wheel', this.wheel);
  }

  private down = (e: PointerEvent) => {
    this.drag = { x: e.clientX, y: e.clientY, button: e.button };
    this.moved = 0;
  };

  private move = (e: PointerEvent) => {
    if (!this.drag) return;
    const dx = e.clientX - this.drag.x, dy = e.clientY - this.drag.y;
    this.drag.x = e.clientX;
    this.drag.y = e.clientY;
    this.moved += Math.abs(dx) + Math.abs(dy);
    if (this.drag.button === 2 || e.shiftKey) {
      this.yaw -= dx * 0.006;
      this.pitch = Math.max(this.minPitch, Math.min(this.maxPitch, this.pitch + dy * 0.005));
    } else {
      // Pan on the XZ plane.
      const k = this.dist * 0.0018;
      const fx = Math.sin(this.yaw), fz = Math.cos(this.yaw);
      this.target.x += (-dx * fz - dy * fx) * k * -1;
      this.target.z += (dx * fx - dy * fz) * k * -1;
    }
    this.update();
  };

  private up = () => {
    this.drag = null;
  };

  private wheel = (e: WheelEvent) => {
    e.preventDefault();
    this.dist = Math.max(this.minDist, Math.min(this.maxDist, this.dist * Math.exp(e.deltaY * 0.0012)));
    this.update();
  };

  update() {
    const cp = Math.cos(this.pitch), sp = Math.sin(this.pitch);
    this.camera.position.set(
      this.target.x + Math.sin(this.yaw) * cp * this.dist,
      this.target.y + sp * this.dist,
      this.target.z + Math.cos(this.yaw) * cp * this.dist,
    );
    this.camera.lookAt(this.target);
  }
}

export { THREE };
